[package]
name = "rust-file-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.6"  # Changed from serde_xml_rs to serde-xml-rs
chrono = "0.4"
env_logger = "0.10"
log = "0.4"